// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skyline.Context;

#nullable disable

namespace Skyline_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Skyline_api.Models.Cidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aeroporto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("aeroporto");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pais");

                    b.HasKey("id");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("Skyline_api.Models.Reserva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<DateOnly>("DataReserva")
                        .HasColumnType("date")
                        .HasColumnName("data_reserva");

                    b.Property<int>("NumPessoas")
                        .HasColumnType("int")
                        .HasColumnName("num_pessoas");

                    b.Property<string>("UsuarioCpf")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("usuario_cpf");

                    b.Property<int>("VooId")
                        .HasColumnType("int")
                        .HasColumnName("voo_id");

                    b.HasKey("id");

                    b.HasIndex("UsuarioCpf");

                    b.HasIndex("VooId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Skyline_api.Models.Usuario", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cpf");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext")
                        .HasColumnName("complemento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("Cpf");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Skyline_api.Models.Voo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Assentos")
                        .HasColumnType("int")
                        .HasColumnName("assentos");

                    b.Property<string>("CompAerea")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comp_aerea");

                    b.Property<DateOnly>("DataPartida")
                        .HasColumnType("date")
                        .HasColumnName("data_partida");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int")
                        .HasColumnName("destino_id");

                    b.Property<int>("NumVoo")
                        .HasColumnType("int")
                        .HasColumnName("num_voo");

                    b.Property<int>("OrigemId")
                        .HasColumnType("int")
                        .HasColumnName("origem_id");

                    b.Property<double>("PrecoUnit")
                        .HasColumnType("double")
                        .HasColumnName("preco_unit");

                    b.HasKey("id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigemId");

                    b.ToTable("Voo");
                });

            modelBuilder.Entity("Skyline.Models.Contato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Resolvido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("resolvido");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("id");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Skyline_api.Models.Reserva", b =>
                {
                    b.HasOne("Skyline_api.Models.Usuario", null)
                        .WithMany("UsuariosReserva")
                        .HasForeignKey("UsuarioCpf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skyline_api.Models.Voo", null)
                        .WithMany("ReservasVoo")
                        .HasForeignKey("VooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Skyline_api.Models.Voo", b =>
                {
                    b.HasOne("Skyline_api.Models.Cidade", "Destino")
                        .WithMany("VoosDestino")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skyline_api.Models.Cidade", "Origem")
                        .WithMany("VoosOrigem")
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("Skyline_api.Models.Cidade", b =>
                {
                    b.Navigation("VoosDestino");

                    b.Navigation("VoosOrigem");
                });

            modelBuilder.Entity("Skyline_api.Models.Usuario", b =>
                {
                    b.Navigation("UsuariosReserva");
                });

            modelBuilder.Entity("Skyline_api.Models.Voo", b =>
                {
                    b.Navigation("ReservasVoo");
                });
#pragma warning restore 612, 618
        }
    }
}
